### ISSUE TITLE
Missing style.css ?

### ISSUE THREAD

**Issue by Marketingguru** [dxritchie/DRDax#1]
Getting an error about style.css missing while trying to import this into chrome.

Could not load css 'style.css' for content script.
{
	"name": "DRDax",
	"description": "GDax Enhancements",
	"version": "1.0",	
	"manifest_version": 2,
	"permissions": [
		"<all_urls>",
		"contextMenus"
	],
	"content_scripts": [
		{
		  "matches": [ "*://www.gdax.com/trade/*"],
		  "css": ["style.css"],
		  "js": ["jquery.min.js",  "tv.js", "edax.js"],
		  "run_at" : "document_idle"
		}
	],
	"background": {
		"scripts": ["menu.js"]
	  },
	"web_accessible_resources": [
        "tv.html"
    ]
}

**Comment by dxritchie** [comment]
Sorry about that pushed up a new version and added in the new BCH pairs to the watchlist for the TV chart.
